### ISSUE TITLE
Question: DBAL dependency

### ISSUE THREAD

**Issue by cyrillkalita** [renoki-co/cashier-register#22]
Laravel 8 throws an error when I try to require `doctrine/dbal:^3.0`
Not a problem to for me to require is as ^2.9, but I checked the migrations folder... why is there a dbal dependency anyway?

**Comment by rennokki** [comment]
`doctrine/dbal` is used as a shield here because when publishing Cashier migrations, some migrations modify the tables. Without `doctrine/dbal`, it throws an error and I required it as a dependency to avoid Cashier-related errors coming from this package. I see that Laravel 8.x supports `doctrine/dbal` to `3.0`, so I might as well just upgrade deps.

**Comment by rennokki** [comment]
`4.1.0` no longer needs doctrine/dbal
