### ISSUE TITLE
Question: syncFeatureUsage over monthly usage

### ISSUE THREAD

**Issue by nickfls** [renoki-co/cashier-register#39]
Perhaps a silly question with an obvious answer:

When I am syncing metered feature use, that is resettable within each billing period, I should account for that in the closure, correct? Something along those lines:

```php
Saas::syncFeatureUsage('minutes', function ($subscription, Feature $feature) {
    return $subscription->billable->minutes()->withinCurrentBillingPeriod()->count();
});
```

Is there a way to pass in the period boundaries to the scope?

**Comment by rennokki** [comment]
The idea is that `syncFeatureUsage` updates the used amount each time the `recordFeatureUsage` is called, to prevent the users for consuming more than they got allocated due to possible sync failures to update the usage in the app.

Calling `recordFeatureUsage` for `minutes` ----> Runs `syncFeatureUsage` for `minutes` and updates the usage ----> Check against the current usage -------> If current usage + the amount to consume is less than the total quota pass, otherwise treat as a special case.

Not sure if this is Stripe with Metric/non-Metric feature or Paddle?
